# Commands to start on workspace startup
tasks:
  - name: "Prepare Environment"
    init: > 
      pip install --upgrade pip &&
      pip install --upgrade setuptools &&
      pip install --upgrade wheel &&
      pip install --upgrade -r requirements.txt &&
      clear
    command: "echo 'VAIIIIIIIIIII!!!!!!'"

# Ports to expose on workspace startup
# ports:
#   - port: 8000
#     onOpen: open-preview
#     visibility: public

vscode:
  extensions:
    - "ms-python.python@2021.9.1218897484"
    - "redhat.vscode-yaml"
    - "tamasfe.even-better-toml"
    - "alexcvzz.vscode-sqlite"
    - "jdinhlife.gruvbox"
